export let button = {
	boxShadow: 'inset 0px 1px 0px 0px #ffffff',
	background: 'linear-gradient(to bottom, #ededed 5%, #dfdfdf 100%)',
	backgroundColor: '#ededed',
	borderRadius: '6px',
	border: '1px solid #dcdcdc',
	display: 'inline-block',
	color: '#777777',
	fontSize: '1rem',
	fontWeight: 'bold',
	padding: '6px 24px',
	textDecoration: 'none',
    textShadow: '0px 1px 0px #ffffff',
    width: '12rem',
    height: '2rem',
}
